# Generated by Django 5.2.12 on 2026-03-09 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UtilisateurCompetence',
            new_name='UserCompetence',
        ),
        migrations.RenameField(
            model_name='usercompetence',
            old_name='utilisateur',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='slot',
            name='activity',
            field=models.CharField(max_length=200),
        ),
    ]
