# Generated by Django 5.2.12 on 2026-03-09 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0002_rename_utilisateurcompetence_usercompetence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='competence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competences.competence'),
            preserve_default=False,
        ),
    ]
