# Generated by Django 5.2.12 on 2026-03-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0003_slot_competence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.DateField(),
        ),
    ]
