# Generated by Django 5.2.12 on 2026-03-10 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0005_alter_slot_creator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='activity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competences.competence'),
        ),
    ]
